name: initialWorkflow
on: 
  push:
    branches: 
      - main
      - release/*

  workflow_dispatch: 


jobs:
  firstJob: 
    runs-on: ubuntu-latest
    steps:
      - run : echo "hello Amchiche"
      - name: Checkout
        uses: actions/checkout@v5
      - name: List files in repository
        run: |
          echo: "The repository   ${{github.repository}} contains the following files : "
          tree
        
    
